edtech_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('account/',include('users.urls'))
]

index/urls.py
from django.urls import path
from . import views

app_name='index'

urlpatterns = [
    path('',views.index,name='index'),
    path('learn/',views.learn,name='learn'),
    path('contact/',views.contact,name='contact'),
    path('communities/',views.communities,name='communities'),
    path('solution/',views.solution,name='solution'),
    path('solution/<str:slug>/',views.paginated_solution,name='paginated solution')
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='users'

urlpatterns = [
    path('register/',auth_views.LoginView.as_view(template_name='users/login.html'),name='register'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout')
    
]

index/models.py
from django.db import models
from django.contrib.auth.models import User
#community name ,community leader, community details , community link ,user

class Contact(models.Model):
    community_name=models.CharField(max_length=50,null=False)
    leader=models.CharField(max_length=50)
    details=models.TextField()
    link=models.URLField(max_length=100)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.link)

    class Meta:
        verbose_name_plural='Contact'

class Dummy(models.Model):
    goal=models.CharField(max_length=200)
    domain=models.CharField(max_length=200)
    interest=models.CharField(max_length=200)
    time=models.IntegerField(default=0)
    pricing=models.CharField(max_length=200)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.goal

    class Meta:
        verbose_name_plural='Dummy'

class Solution(models.Model):
    course_name=models.CharField(max_length=100)
    course_link=models.URLField(max_length=50)
    platform=models.CharField(max_length=20)
    slug=models.SlugField(max_length=35,null=False,blank=False,default='default/slug')

    def __str__(self):
        return self.course_name
    
    class Meta:
        verbose_name_plural='Solution'

users/models.py
from django.db import models

index/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Contact,Dummy,Solution
from django.contrib import messages
import bs4 
import requests

def index(request):
    return render(request,'index/index.html')


@login_required
def learn(request):
    if request.method == 'POST':
        goal=request.POST.get('goal')
        domain=request.POST.get('domain')
        interest=request.POST.get('interest')
        time=request.POST.get('time')
        pricing=request.POST.get('pricing')
        user=request.user
        entryy=Dummy(goal=goal,domain=domain,interest=interest,time=time,pricing=pricing,user=user)
        entryy.save()
        return render(request,'index/solution.html')
    return render(request,'index/getstarted.html')


@login_required
def contact(request):
    if request.method=='POST':
        name=request.POST.get('name')
        leader=request.POST.get('leader')
        details=request.POST.get('details')
        link=request.POST.get('link')
        user=request.user
        print(details)
        entry=Contact(name=name,leader=leader,details=details,link=link,user=user)
        print(details)
        entry.save()
        messages.success(request,'Request Sent!')
        return render(request,'index/index.html')
    return render(request,'index/contact.html')

def communities(request):
    qset= Contact.objects.all()
    return render(request,'index/communities.html',{'qset':qset})



@login_required
def solution(request):
    qset2=Solution.objects.all()
    return render(request,'index/solution.html',{'qset2':qset2})

@login_required
def paginated_solution(request,slug):
    qset3=Solution.objects.filter(slug=slug)
    return render(request,'index/paginated.html',{'qset3':qset3})

users/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib import messages

def register(request):
    if request.method=='POST':
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        confirm_password=request.POST.get('confirm_password')
        if password==confirm_password:
            db_entry=User.objects.create_user(username=username,email=email,password=password)
            db_entry.save()
            return render(request,'users/login.html')
    return render(request,'users/login.html')

index/templates/index/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock title %} </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'landingPage.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,800;1,500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
</head>
<body>
    <div class="header">
    <div class="container">
        <div class="navbar">
            <div class="logo">
                <img src="{% static 'logologo.png' %}" width = "150px">
            </div>
            <nav>
                <ul id="MenuItems">
                    <li><a href="{% url 'index:index' %}">Home</a></li>
                    <li><a href="{% url 'index:learn' %}">Get Started</a></li>
                    <li><a href="{% url 'index:communities' %}">Communities</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'index:contact' %}">Contact Us <i class="fas fa-user"></i></a></li>
                    <li><a href="{% url 'users:logout' %}">{{user.username}} || Logout <i class="fas fa-user"></i></a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}">Login <i class="fas fa-user"></i></a></li>
                    {% endif %} 
                </ul>
            </nav>
            <li style="list-style: none;" class="menu-icon" onclick="menutoggle()"><i class="fas fa-bars"></i></li>
        </div>

{% block content %} {% endblock content %}

   <!-------- FOOTER --------->
    <div class="footer">
    <div class="container">
        <div class="row">
            <div class="footer-col-1">
                <h3>Download Our App</h3>
                <p>Lorem ipsum dolor sit amet consectetur.</p>
                <div class="app-logo">
                 <img src="{% static 'App1.png'%}">
                 <img src="{% static 'App2.png'%}">
             </div>
            </div>
            <div class="footer-col-2">
             <img src="{% static 'logologo.png'%}" width="170px">
             <p>Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet consectetur.</p>
           </div>
          <div class="footer-col-3">
             <div class="txt">
             <h3>Useful Links</h3>
             <ul>
                 <li>Coupons</li>
                 <li>Blog Post</li>
                 <li>Return Policy</li>
                 <li>Join Affiliate</li>
             </ul>
             </div>
             <div class="txt">
                 <h3>Follow us</h3>
                 <ul>
                     <li>Facebook</li>
                     <li>Twitter</li>
                     <li>Instagram</li>
                     <li>Youtube</li>
                 </ul>
              </div>
         </div>
    </div>
    <hr>
    <p class="copyright">Copyright &#169 2021 - PK</p>
</div>


<script src="{% static 'landingPage.js'%}"></script>
</body>
</html>

index/templates/index/communities.html
{% extends "index/base.html" %}
{% block title %}COMMUNITIES {% endblock title %}
{% block content %}

        {% for object in qset %}
            <strong><h3>{{object.user}}</h3></strong><br>
            <h1>{{object.community_name}} </h1><br>
            <h4>{{object.leader}}</h4><br>
            <br>
            <p>{{object.details}}</p><br>
            <a href="{{object.course_link}}"><button type="menu">Join</button></a>
        {% endfor %}
{% endblock content %}

index/templates/index/contact.html
{% extends 'index/base.html' %}
{% block title %}CONTACT {% endblock title %}

{% block content %}

<!--Section: Contact v.2-->
<section class="mb-4" style="color: white"
>

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form name="sentMessage" method="POST">
                {% csrf_token %}
                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Community Name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="leader" name="leader" class="form-control">
                            <label for="leader" class="">Community Leader</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="link" name="link" class="form-control">
                            <label for="link" class="">Community Link</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="details" name="details" rows="2" class="form-control md-textarea"></textarea>
                            <label for="details">About Community</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->
                <div class="form-group">
                    <button type="submit" class="btn btn-primary"  id="sendMessageButton" >Send</button>
                  </div>
            </form>

        </div>
    </div>
</section>

{% endblock content %}

index/templates/index/getstarted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <form method="POST">
      {% csrf_token %}
        <div id="center">
        <div class="form-group">
          <label for="goal" >1. What's your goal?</label>
          <input type="text" class="form-control" id="goal" name="goal" aria-describedby="emailHelp" placeholder="goal oriented learning is always better">
          <small id="emailHelp" class="form-text text-muted">Write something like: Freelancing, Personality development, upgrading skills, career or hobby.</small>
        
          <div class="form-group">
            <label for="domain">2. In which domain you are interested in?</label>
            <small id="domain" name="domain" class="form-text text-muted">GOAL -> FREELANCING</small>
            <input type="text" class="form-control" id="domain" name="domain" aria-describedby="emailHelp" placeholder="choose domain">
            <small id="emailHelp" class="form-text text-muted">Write one of these: <br>Graphics & Design
              <br>Digital Marketing
              <br>Writing & Translation
              <br>Video & Animation
              <br>Music & Audio
              <br>Programming & Tech
              <br>Data 
              <br>Business
              <br>Lifestyle
          </small>
          </div>
          
            <div class="form-group">
              <label for="interest">3. Choose what's suitable for you?</label>
              <small id="interest" class="form-text text-muted">DOMAIN -> PROGRAMMING AND TECH</small>
              <input type="text"  name="interest" class="form-control" id="interest" aria-describedby="emailHelp" placeholder="choose domain">
              <small id="emailHelp" class="form-text text-muted">Write one of these: <br>WordPress
                <br>Website Builders & CMS
                <br>Game Development
                <br>Development for Streamers
                <br>Web Programming
                <br>E-Commerce Development
                <br>Mobile Apps
                <br>Desktop Applications
                <br>Support & IT
                <br>Get Your Website in a Few Steps
                <br>Chatbots
                <br>Online Coding LessonsNEW
                <br>Cybersecurity & Data Protection
                <br>Convert Files
                <br>User Testing
    </small>
            </div> 
              <div class="form-group">
                <label for="time">4. How much time you can dedicate in weeks?</label>
                <small id="time" class="form-text text-muted">SUB -DOMAIN -> WEB PROGRAMMING</small>
                <input type="text" name="time" class="form-control" id="time" aria-describedby="emailHelp" placeholder="time in weeks">
                <small id="emailHelp" class="form-text text-muted">Write the number of weeks you think is ideal for you.
      </small>
              </div>
              
                <div class="form-group">
                  <label for="pricing">5. What you you prefer - paid course / free?</label>
                  <small id="pricing" class="form-text text-muted">SUB -DOMAIN -> WEB PROGRAMMING</small>
                  <input type="text" name="pricing" class="form-control" id="pricing" aria-describedby="emailHelp" placeholder="paid/free">
                  <small id="emailHelp" class="form-text text-muted">Type either "Paid" or "Free".
        </small>
                </div>
                <button type="Submit" class="btn btn-primary">Submit</button>
        </div>
        <br><br>
          <a href="{%  url 'index:index'%}">HOME</a>
      </form>
    </div>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
<style>
    #center{
        padding: 100px 50px 100px;
    }
</style>
</body>
</html>

index/templates/index/index.html
{% extends 'index/base.html' %}
{% block title %}INDEX {% endblock title %}

{% block content %}
{% load static %}

<div class="row">
    <div class="col-2">
        <h1>Great First <br>Headline Here</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. <br>Delectus officiis beatae odit laboriosam saepe dolore soluta, rem ad sit ratione.</p>
        {% if user.is_authenticated %}
        <a href="{% url 'index:learn' %}" class="btn">Get Started &#8594</a>
        {% else %}
        <a href="{% url 'users:register' %}" class="btn">Login</a>
        {% endif %}
    </div>
    <div class="col-2">
        <img src="{% static 'graphics.png' %}">
    </div>
</div>
</div>
</div>
    
    <!---------TESTIMONIAL---------->
   <div class="testimonial">
       <div class="small-container">
           <div class="row">
               <div class="col-4">
                <i class="fas fa-quote-left"></i>
                   <p style="color: black;">Lorem ipsum dolor elit. Ut quod et fugit sit atque quam nemo laudantium dolore quisquam possimus nam?</p>
                   <div class="center-text">
                   <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                    <i class="far fa-star"></i>
                </div>
                <img src="{% static  'Profile Photo.png' %}">
                <h3>John Doe</h3>
                  </div>
               </div>
               <div class="col-4">
                <i class="fas fa-quote-left"></i>
                   <p style="color: black;">Lorem ipsum dolor elit. Ut quod et fugit sit atque quam nemo laudantium dolore quisquam possimus nam?</p>
                   <div class="center-text">
                   <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                    <i class="far fa-star"></i>
                </div>
                <img src="{% static  'Profile Photo.png' %}">
                <h3>John Doe</h3>
                  </div>
               </div>
               <div class="col-4">
                <i class="fas fa-quote-left"></i>
                   <p style="color: black;">Lorem ipsum dolor elit. Ut quod et fugit sit atque quam nemo laudantium dolore quisquam possimus nam?</p>
                   <div class="center-text">
                   <div class="rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                    <i class="far fa-star"></i>
                </div>
                <img src="{% static 'Profile Photo.png' %}">
                <h3>John Doe</h3>
                  </div>
               </div>
            </div>
       </div>
   </div>
   <!--------- BRANDS  --------->
   .<div class="brands">
       <div class="small-container">
           <div class="row">
               <div class="col-5">
                   <img src="{% static 'udemy.png'%}">
                </div>
                <div class="col-5">
                    <img src="{% static 'coursera.png' %} ">
                 </div>
                 <div class="col-5">
                    <img src="{% static 'udacity.png' %} ">
                 </div>
                 <div class="col-5">
                    <img src="{% static 'edx.png' %}">
                 </div>
                 <div class="col-5">
                    <img src="{% static 'bl.png' %}">
                 </div>
           </div>
       </div>
   </div>
{% endblock content %}

index/templates/index/paginated.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paginated View</title>
</head>
<body>
{% for qs3 in qset3 %}
<h1>{{qs3.course_name}}</h1>
<h2>{{qs3.platform}}</h2>
<a href="{{qs3.course_link}}"><button type="menu">COURSE LINK</button></a>
{% endfor %}
    
</body>
</html>

index/templates/index/search.html
{% extends "index/base.html" %}
{% block title %}{{searched}} {% endblock title %}
{% block content %}

{% if searched %}
<p>You searched {{searched}}..</p>
{% endif %}

{% if x3 %}
{{x3}}
{% endif %}

{% if x1 %}
{% for i1 in x1 %}
{{i1.community_name}}
{{i1.leader}}
{{i1.details}}
{{i1.link}}
{{i1.user}}
{% endfor %}
{% else %}
<p> No result found for {{searched}}</p>
{% endif %}

{% endblock content %}

index/templates/index/solution.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <form>
        <div id="center">
        <div class="form-group">
            <h1>BROCHURE</h1>
          <label for="exampleInputEmail1">Click on the link below to get you road map for your journey.</label><br>
          <small style="color:grey">The roadmap serves as a guide for the team during their journey, allowing them to recognize and act on events that require a change of direction.</small><br>
          <a href="https://github.com/kamranahmedse/developer-roadmap">ROAD MAP</a><br>
          <small style="color:grey">These are the courses you'll need to learn the required skills.</small><br>
          <label for="exampleInputEmail1">Click on the link below to get course links.</label><br>
          {% for query in qset2 %}
          <a href="{{query.slug}}"><button>{{query.course_name}}</button></a><br>
          {% endfor %}
          <small style="color:grey;">Having a sense of community unites us. Being a part of a community can make us feel as though we are a part of something greater than ourselves. It can give us opportunities to connect with people, to reach for our goals, and makes us feel safe and secure. It's important for every person to have a sense of community.</small>
          <br><label for="exampleInputEmail1">Click on the link below to join the community.</label><br>
          <a href="https://discord.com/invite/ukhrVx4kyp">JOIN SERVER HERE</a><br>
          <a href="https://discord.com/invite/ukhrVx4kyp">JOIN OUR COMMUNITY</a><br>
        <br><br>
          <a href="{% url 'index:index' %}">HOME</a>
          <small style="color:grey;">Having a sense of community unites us. Being a part of a community can make us feel as though we are a part of something greater than ourselves. It can give us opportunities to connect with people, to reach for our goals, and makes us feel safe and secure. It's important for every person to have a sense of community.</small>
          <br><label for="exampleInputEmail1">Click on the link below to join the community.</label><br>
          <a href="https://discord.com/invite/ukhrVx4kyp">JOIN SERVER HERE</a><br>
          <a href="https://discord.com/invite/ukhrVx4kyp">JOIN OUR COMMUNITY</a><br>
        <br><br>
          <a href="{% url 'index:index' %}">HOME</a>
          <!-- <small id="emailHelp" class="form-text text-muted">Type either "Paid" or "Free".
</small> -->
        <!-- </div>
        <button type="Previous" class="btn btn-primary"><a href="Question4.html" style="color: white;">Previous</a></button>
        <button type="Submit" class="btn btn-primary"><a href="solution.html" style="color: white;">Submit</a></button>
    </div> -->

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   
<style>
    #center{
        padding: 100px 50px 50px 100px;
    }
</style>
</body>
</html>

users/templates/users/login.html
{% extends "index/base.html" %}
{% block title %}LOGIN {% endblock title %}
{% block content %}


<!-- ----------- ACCOUNT PAGE ----------- -->
<div class="account-page">
    <div class="container">
        <div class="row">
            <div class="col-2">
                {% load static %}
                <img src="{% static 'login.png'%}" width="100%">
            </div>
            <div class="col-2">
                <div class="form-container">
                    <div class="form-btn">
                        <span onclick="login()">Login</span>
                        <span onclick="register()">Register</span>
                        <hr id="Indicator">
                    </div>

                    <form id="LoginForm" method="POST">
                        {% csrf_token %}
                        <div class="field">
                        {{form.as_p}}
                        </div>
                        <button type="submit" class="btn">Login</button>
                        <a href="{% url 'users:register' %}">No Account?Register</a>
                    </form>

                    <form id="RegForm" method= "POST" >
                        {% csrf_token %}
                        <input type="text" id="username" name="username" placeholder="Username">
                        <input type="email" id="email" name="email" placeholder="Email">
                        <input type="password" id="password" name="password" placeholder="Password">
                        <input type="password"  id="confirm_password"  name="confirm_password" placeholder="Confirm Password">
                        <button type="submit" class="btn btn-primary" >Register</button>
                        <a href="{% url 'users:register' %}">Already have an account?Login</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
<h2>LOGGED OUT!</h2>

<a href="{% url 'users:register' %}"><strong><h3>Login again</h3></strong></a>